apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian-deployment
  namespace: test01
  labels:
    app: debian10
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: debian10
  template:
    metadata:
      labels:
        app: debian10
        app.kubernetes.io/app: "debian10"
    spec:
      containers:
      - name: debian10
        image: debian:10
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME"]
          readOnlyRootFilesystem: true
        command:
        - sleep
        - "36000000"
        volumeMounts:
          - mountPath: /var/run
            name: tmpfs-1
          - mountPath: /var/cache
            name: tmpfs-2
          - mountPath: /var
            name: tmpfs-3
      volumes:
        - name: tmpfs-1
          emptyDir: {}
        - name: tmpfs-3
          emptyDir: {}
        #- name: tmpfs-ram
        #  emptyDir:
        #    medium: "Memory"
        - name: tmpfs-2
          emptyDir: {}

