apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-argocd-service
spec:
  selector:
    app: nginx-argocd-lb
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-argocd-lb
spec:
  selector:
    matchLabels:
      app: nginx-argocd-lb
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-argocd-lb
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
